Fix missing slashes
The command failure without slash

root@DESKTOP-8AEEQ9G:/mnt/c/Workspace/htdocs/Projetos/zend-album-test# sqlite3 data/zftutorial.db data/posts.schema.sql
Error: near "data": syntax error